### ISSUE TITLE
Completion and arguments display

### ISSUE THREAD

**Issue by silgon** [syohex/emacs-company-jedi#2]
Hello, I just tried to install company-jedi. Here is the relevant part of the code

```lisp
(require 'company-jedi)
(autoload 'jedi:setup "jedi" nil t)
(add-hook 'python-mode-hook 'jedi:setup)
(add-to-list 'company-backends 'company-jedi)
```

So, I'm having the following question. When you're using auto-complete package you have the function and the description of the function. Then when you're inside the arguments, the proper arguments that you have to put inside the functions are displayed. Nonetheless, here I can only see the completion, without any knowledge if it's a function, variable or whatsoever, and I cannot see the the arguments while I'm inside the function. Is this normal?

**Comment by syohex** [comment]
There is bug of it in `jedi-core`. I'll fix it later.

**Comment by syohex** [comment]
@silgon I've fixed `emacs-jedi` about this issue. Please upgrade `jedi-core` and retry.

**Comment by the-max0r** [comment]
Same here. jedi with auto-complete works fine, but with company-jedi only the completion works. No description is shown and by pressing F1 in the completion list, the minibuffer says "No documentation available". And in an argument list of a function the minibuffer says "deferred error : (void-variable auto-complete-mode)".
I'm using jedi-core 20150528.2022 and company-jedi 20150517.217 from melpa.

**Comment by syohex** [comment]
> And in an argument list of a function the minibuffer says deferred error : (void-variable auto-complete-mode).

I suppose latest `jedi-core.el` never says such error message.
`jedi-core.el` check whether `auto-complete-mode` is defined before using its value.

Please reinstall `jedi-core.el` after removing it, and try again.

**Comment by syohex** [comment]
Sorry I found a bug. Please wait

**Comment by syohex** [comment]
I have fixed at https://github.com/tkf/emacs-jedi/pull/237. Please check latest version

**Comment by the-max0r** [comment]
Sorry, the error is still the same. Even tried a fresh `~/.emacs.d/` only containing `init.el` with the following content
`(add-hook 'python-mode-hook 'company-mode)
(company-quickhelp-mode 1)

(autoload 'jedi:setup "jedi" nil t)
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)                 ; optional

(add-to-list 'company-backends 'company-jedi)`

**Comment by syohex** [comment]
Do you use jedi-core `20150611.254` ?
It works as following gif animation.

![company-jedi](https://cloud.githubusercontent.com/assets/554281/8110035/10c49194-1095-11e5-8df2-15a4336ee98e.gif)

**Comment by the-max0r** [comment]
After updating to jedi-core `20150611.254` it works as expected! Thanks.

**Comment by syohex** [comment]
> But documentation still doesn't work with company-quickhelp like in Lisp-Buffers:

`company-jedi` does not implement this feature yet.
I should implement this feature.

**Comment by syohex** [comment]
@the-max0r I have implemented and merged at #3. Please check latest version.

**Comment by the-max0r** [comment]
Works like a charm. Thanks a lot!

**Comment by jack836** [comment]
Could not get function signatures to be displayed in mini buffer as shown [here](https://github.com/syohex/emacs-company-jedi/issues/2#issuecomment-111161692)

Some points of concern

* I am using the latest emacs-27 
* I run emacs inside the terminal using the -nw option

The output of `jedi:show-setup-info` is as follows

`; Emacs Lisp version:
(:emacs-version "27.0.50" :jedi-version "0.2.7" :python-environment-version "0.0.2alpha0")
;; Python version:
((:version "3.5.3 (default, Jan 19 2017, 14:11:04) \n[GCC 6.3.0 20170118]" :file nil :name "sys")
 (:version "0.12.0" :file "/home/svi/.emacs.d/.python-environments/default/lib/python3.5/site-packages/jedi/__init_\
_.py" :name "jedi")
 (:version "0.0.5" :file "/home/svi/.emacs.d/.python-environments/default/lib/python3.5/site-packages/epc/__init__.\
py" :name "epc")
 (:version "0.0.3" :file "/home/svi/.emacs.d/.python-environments/default/lib/python3.5/site-packages/sexpdata.py" \
:name "sexpdata"))
;; Command line:
(:virtualenv "/home/svi/.virtualEnvs/python3/bin/virtualenv" :virtualenv-version "15.2.0\n")
;; Customization:
((jedi:complete-on-dot . t)
 (jedi:doc-display-buffer . display-buffer)
 (jedi:doc-hook view-mode)
 (jedi:doc-mode . rst-mode)
 (jedi:environment-root)
 (jedi:environment-virtualenv)
 (jedi:get-in-function-call-delay . 1000)
 (jedi:get-in-function-call-timeout . 3000)
 (jedi:goto-definition-config
  (nil nil nil)
  (t nil nil)
  (nil definition nil)
  (t definition nil)
  (nil nil t)
  (t nil t)
  (nil definition t)
  (t definition t))
 (jedi:goto-definition-marker-ring-length . 16)
 (jedi:imenu-create-index-function . jedi:create-nested-imenu-index)
 (jedi:import-python-el-settings . t)
 (jedi:install-imenu)
 (jedi:install-python-jedi-dev-command "pip" "install" "--upgrade" "git+https://github.com/davidhalter/jedi.git@dev\
#egg=jedi")
 (jedi:key-complete .
                    [C-tab])
 (jedi:key-goto-definition .
                           [67108910])
 (jedi:key-goto-definition-pop-marker .
                                      [67108908])
 (jedi:key-related-names . "^Cr")
 (jedi:key-show-doc . "^Cd")
 (jedi:server-args)
 (jedi:server-command "/home/svi/.emacs.d/.python-environments/default/bin/jediepcserver")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))
`

I love this feature and would be great if if works. Any help is highly appreciated.
